os: linux
dist: xenial
language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0'
cache:
  directories:
    - vendor
before_script:
  - composer update --dev --no-interaction
script:
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit
  - vendor/bin/phpcs