name: Tests
on: [push, pull_request]
env:
    CI: true

jobs:
    run:
        name: PHP ${{ matrix.php }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                php: ['7.4', '7.3', '7.2']

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run tests
              run: ./vendor/bin/phpunit
